/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HidroizolatiiTeraseCirculabileRouteImport } from './routes/hidroizolatii-terase-circulabile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HidroizolatiiTeraseCirculabileRoute =
  HidroizolatiiTeraseCirculabileRouteImport.update({
    id: '/hidroizolatii-terase-circulabile',
    path: '/hidroizolatii-terase-circulabile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hidroizolatii-terase-circulabile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hidroizolatii-terase-circulabile'
  id: '__root__' | '/' | '/hidroizolatii-terase-circulabile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HidroizolatiiTeraseCirculabileRoute: typeof HidroizolatiiTeraseCirculabileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidroizolatii-terase-circulabile': {
      id: '/hidroizolatii-terase-circulabile'
      path: '/hidroizolatii-terase-circulabile'
      fullPath: '/hidroizolatii-terase-circulabile'
      preLoaderRoute: typeof HidroizolatiiTeraseCirculabileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HidroizolatiiTeraseCirculabileRoute: HidroizolatiiTeraseCirculabileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
